# Generated by Django 2.0.7 on 2018-08-13 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decisor',
            old_name='nome',
            new_name='name',
        ),
    ]
