# Generated by Django 2.0.7 on 2018-08-13 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_web', '0002_auto_20180813_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternativa',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='criterio',
            old_name='nome',
            new_name='name',
        ),
    ]
