# Generated by Django 2.0.7 on 2018-08-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_web', '0002_auto_20180815_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d1c1c2', models.IntegerField()),
                ('d1c1c3', models.IntegerField()),
                ('d1c2c3', models.IntegerField()),
                ('d2c1c2', models.IntegerField()),
                ('d2c1c3', models.IntegerField()),
                ('d2c2c3', models.IntegerField()),
                ('d3c1c2', models.IntegerField()),
                ('d3c1c3', models.IntegerField()),
                ('d3c2c3', models.IntegerField()),
            ],
        ),
    ]
