# Generated by Django 2.0.7 on 2018-08-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_web', '0003_criterios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliardois',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1a1a2', models.IntegerField()),
                ('c1a1a3', models.IntegerField()),
                ('c1a2a3', models.IntegerField()),
                ('c2a1a2', models.IntegerField()),
                ('c2a1a3', models.IntegerField()),
                ('c2a2a3', models.IntegerField()),
                ('c3a1a2', models.IntegerField()),
                ('c3a1a3', models.IntegerField()),
                ('c3a2a3', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Avaliartres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1a1a2', models.IntegerField()),
                ('c1a1a3', models.IntegerField()),
                ('c1a2a3', models.IntegerField()),
                ('c2a1a2', models.IntegerField()),
                ('c2a1a3', models.IntegerField()),
                ('c2a2a3', models.IntegerField()),
                ('c3a1a2', models.IntegerField()),
                ('c3a1a3', models.IntegerField()),
                ('c3a2a3', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Avaliarum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1a1a2', models.IntegerField()),
                ('c1a1a3', models.IntegerField()),
                ('c1a2a3', models.IntegerField()),
                ('c2a1a2', models.IntegerField()),
                ('c2a1a3', models.IntegerField()),
                ('c2a2a3', models.IntegerField()),
                ('c3a1a2', models.IntegerField()),
                ('c3a1a3', models.IntegerField()),
                ('c3a2a3', models.IntegerField()),
            ],
        ),
    ]
